import strictPreset from "./tools/oxlint/rikalabs-strict.json" with { type: "json" };
import { defineConfig } from "oxlint";
import { fileURLToPath } from "node:url";

/**
 * JS/TS linting for the dashboard frontend.
 *
 * Two strict layers on top of oxlint's default categories:
 *
 * 1. `tools/oxlint/rikalabs-strict.json` — a flattened, checked-in copy of the
 *    `strict` preset from @rikalabs/oxlint-standards (see
 *    tools/flatten_rikalabs_strict.py). It is flattened because the published
 *    presets reference a few rules oxlint 1.83.0 does not implement, and oxlint
 *    rejects configs that mention unknown rules even as "off".
 * 2. The vendored anti-slop plugin (tools/oxlint/anti-slop — a curated copy of
 *    dmmulroy/anti-slop, MIT) that rejects low-evidence patterns typical of
 *    AI-generated code. Keep it in sync with upstream dmmulroy/anti-slop.
 *
 * The Rika-Labs standards are TypeScript-first (they assume type-aware rules).
 * The flattened preset carries `options.typeAware: false`, so those rules are
 * off and `tsc --noEmit` over `web/tsconfig.json` is the only thing checking
 * the type settings; the few platform exceptions below are documented.
 */
export default defineConfig({
  extends: [strictPreset],
  ignorePatterns: [
    "node_modules/**",
    // Generated by the Vite build from web/ — lint the sources, not the output.
    "src/recoverage/assets/app.js",
    "src/recoverage/assets/style.css",
    // The vendored anti-slop plugin itself.
    "tools/oxlint/anti-slop/**",
  ],
  // The frontend is browser-only.
  env: { browser: true },
  jsPlugins: [
    // oxlint passes plugin specifiers to Node `import()` verbatim, so use
    // absolute paths resolved from this config file rather than bare names.
    {
      name: "@rikalabs",
      specifier: fileURLToPath(
        new URL(
          "./node_modules/@rikalabs/oxlint-standards/dist/plugin/index.js",
          import.meta.url,
        ),
      ),
    },
    {
      name: "anti-slop",
      specifier: fileURLToPath(
        new URL("./tools/oxlint/anti-slop/index.ts", import.meta.url),
      ),
    },
    {
      name: "shadcn",
      specifier: fileURLToPath(
        new URL("./node_modules/@shadcn/lint/dist/index.js", import.meta.url),
      ),
    },
  ],
  settings: {
    // @shadcn/lint reads the classes Tailwind can generate from the stylesheet
    // `components.json` names (web/app/index.css, which imports the relumea
    // tokens), so a class outside the token set is an unknown class here.
    shadcn: {
      componentImports: ["^@/components/ui(/|$)"],
      note: "Tokens come from web/app/system/tokens.css, a verbatim copy of relumea.ai's. A value the system lacks is proposed there first.",
    },
  },
  rules: {
    // The preset's oxc/no-new-buffer does not exist in oxlint 1.83.0; the
    // same rule lives under unicorn. Keep the preset's intent.
    "unicorn/no-new-buffer": "error",
    // Browser-only SPA: `window` is the precise, self-documenting global;
    // globalThis buys nothing when there is no non-browser runtime.
    "unicorn/prefer-global-this": "off",
    // The built bundle is loaded as a classic <script>, not an ES module.
    "import/unambiguous": "off",
    // Pedantic nesting heuristic; 40+ low-signal sites in UI glue code.
    "unicorn/max-nested-calls": "off",
    // `!= null` is the idiomatic nullish check (catches null and undefined);
    // strict comparisons there would only add noise. eqeqeq keeps enforcing
    // === everywhere else.
    "eslint/eqeqeq": ["error", "always", { "null": "ignore" }],
    "eslint/no-eq-null": "off",
    // Style choices that are deliberate conventions in this codebase:
    // - one-var "always" would merge section-organized declarations into one
    //   giant chain; "never" still enforces single-declarator statements.
    "eslint/one-var": ["error", "never"],
    // - single-line `if (x) return y;` guards stay brace-free; multi-line
    //   blocks must use braces (no dangling-else hazards).
    "eslint/curly": ["error", "multi-line"],
    // - comment capitalization/placement is editorial, not contractual.
    "eslint/capitalized-comments": "off",
    "eslint/no-inline-comments": "off",
    // - hoisted function declarations for helpers, const arrows for
    //   callbacks; declarations grouped by domain order, not alphabet.
    "eslint/func-style": "off",
    "eslint/sort-vars": "off",
    // Closures only run after the IIFE has finished, so a later const is
    // initialized before the call. Reordering would invert domain grouping.
    "eslint/no-use-before-define": "off",
    // The shell component is ~600 lines of topbar orchestration and the panel
    // ~500; the 60-line cap would force artificial fragmentation.
    "eslint/max-lines-per-function": "off",
    // _-prefixed fields (cell._baseClass etc.) mark derived caches written
    // onto data objects; the underscore is the convention that separates them
    // from the API fields (cell.state, cell.start, ...).
    "eslint/no-underscore-dangle": "off",
    // Classic-script IIFE pattern: these helpers are scoped to the IIFE, and
    // "module level" would mean the global scope — worse, not better.
    "unicorn/consistent-function-scoping": "off",
    // Script loading has no non-Promise await; new Promise(resolve) on
    // el.onload is the standard idiom.
    "promise/avoid-new": "off",
    // Plain-object dictionaries cleared via delete; a TypeScript-targeted
    // rule with no type info here.
    "typescript/no-dynamic-delete": "off",
    // The rule's suggested fix (Number(x) for parseFloat(x)) breaks computed
    // CSS lengths: Number("12px") is NaN while parseFloat("12px") is 12.
    "unicorn/prefer-number-coercion": "off",
    // Enforced from the preset: the van.tags destructures (`a`, `p`, ...) are
    // element factories, so a local reusing those names hides an HTML tag.
    // Real collisions are fixed by rename, not by turning the rule off.
    "eslint/no-shadow": "error",
    // Vendored anti-slop rules (dmmulroy), enforced on top of the preset.
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    // @shadcn/lint: the design-system rules. Colours, sizes, radii and
    // shadows come from the token layer only.
    "shadcn/no-raw-colors": "error",
    "shadcn/no-arbitrary-values": "error",
    // The allowed names are hooks, not styles: print.css, the dialog's inert
    // query and the browser specs select on them, and none carries a rule.
    "shadcn/no-unknown-classes": [
      "error",
      {
        allow: [
          "actions",
          "filter-btn",
          "filters",
          "hint",
          "legend",
          "meta-item",
          "meta-label",
          "meta-value",
          "modal",
          "modal-actions",
          "modal-close",
          "modal-content",
          "modal-header",
          "modal-title",
          "panel",
          "panel-actions",
          "panel-head",
          "panel-title",
          "search",
          "search-result",
          "search-results",
          "search-row",
          "section",
          "section-actions",
          "section-title",
          "section-title-text",
          "skip-link",
          "source-link",
          "stats",
          "tab-btn",
          "tabs",
          "title",
          "topbar",
        ],
      },
    ],
    "shadcn/no-inline-styles": "error",
    "shadcn/require-static-classes": "error",
  },
  overrides: [
    {
      // web/app/system is a verbatim copy of relumea.ai's src/system, which
      // declares props with `interface`. The copy is never edited.
      files: ["web/app/system/**"],
      rules: {
        "typescript/consistent-type-definitions": "off",
      },
    },
    {
      // vitest rules only apply to test files; the webui assets are never
      // tests, and oxlint does not scope vitest rules by file pattern itself.
      files: ["src/recoverage/assets/**"],
      rules: {
        "vitest/no-conditional-tests": "off",
        "vitest/no-import-node-test": "off",
        "vitest/prefer-called-once": "off",
        "vitest/consistent-test-filename": "off",
        "vitest/prefer-called-times": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/prefer-to-be-object": "off",
        "vitest/require-hook": "off",
      },
    },
    {
      // The React frontend's sources are never tests either; the same vitest
      // rules misfire on a module-level `registerLanguage` call and on the
      // entry's mount. The app itself is held to every other rule, and the
      // anti-slop set in particular.
      files: ["web/app/**"],
      rules: {
        "vitest/no-conditional-tests": "off",
        "vitest/no-import-node-test": "off",
        "vitest/prefer-called-once": "off",
        "vitest/consistent-test-filename": "off",
        "vitest/prefer-called-times": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/prefer-to-be-object": "off",
        "vitest/require-hook": "off",
      },
    },
    {
      // CLI tooling may log to stdout/stderr, use Node builtins, sync fs and
      // `./`-relative URLs (the Rika preset already makes this exception for
      // tools, but only for .ts/.mts/.cts — cover .js too).
      files: ["tools/**", "*.config.{ts,js,mjs,cjs}"],
      rules: {
        "eslint/no-console": "off",
        "import/no-nodejs-modules": "off",
        "node/no-sync": "off",
        "unicorn/import-style": "off",
        "unicorn/prefer-import-meta-properties": "off",
        "unicorn/relative-url-style": "off",
        "vitest/no-conditional-tests": "off",
        "vitest/no-import-node-test": "off",
        "vitest/prefer-called-once": "off",
        "vitest/consistent-test-filename": "off",
        "vitest/prefer-called-times": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/prefer-to-be-object": "off",
        "vitest/require-hook": "off",
      },
      globals: { process: "readonly" },
    },
  ],
});
