#!/usr/bin/env python3
"""Write `FULL_FOLD` in `web/app/lib/format.ts` from `str.casefold`.

The SPA's search folds through `format.foldForSearch`, which mirrors
`server.fold_text` (NFC composition plus `str.casefold`) as far as JavaScript
can. `String.prototype.toLowerCase` has no operator for full case folding's
one-to-many mappings, so `foldForSearch` carries a table for the characters
where the two disagree. That table used to be ten hand-picked ligatures, and a
table written that way cannot be checked against the operator it stands in
for: `tests/test_server.py` derived its cases FROM the table, so a wrong or
incomplete table passed. It was incomplete — 173 code points were missing, and
`µ` (MICRO SIGN) against `μ` (GREEK SMALL MU) is a firmware symbol name, not an
exotic one.

This computes the whole set, so the table and the operator cannot drift.
`tests/test_server.py::test_the_spa_fold_expansions_cover_every_casefold`
holds the shipped table against `str.casefold` over every scalar code point,
which is the check a hand-written table cannot pass.

Run it after a Unicode version bump:

    python tools/gen_full_fold.py            # print what would change
    python tools/gen_full_fold.py --write    # rewrite format.ts
"""

from __future__ import annotations

import argparse
import pathlib
import sys

_ROOT = pathlib.Path(__file__).resolve().parent.parent
_FORMAT_TS = _ROOT / "web" / "app" / "lib" / "format.ts"

_BEGIN = "  // GENERATED by tools/gen_full_fold.py -- edit that, not this.\n"

_PER_LINE = 3


def full_fold_table() -> dict[str, str]:
    """Every code point `toLowerCase` leaves alone and `casefold` rewrites.

    The condition is the whole definition of the table's contents. A code
    point `toLowerCase` rewrites has already been rewritten by the time
    `foldForSearch` reaches its replace pass, so it can never be the character
    that matches, and putting it in the class would widen the pattern with a
    key that is never present. Everything else whose `casefold` differs from
    itself is a key, and the value is what `casefold` produces.

    Surrogates are skipped: they are not scalar values, `casefold` leaves them
    alone, and a document cannot spell one (`tomllib` refuses `\\uD800`).
    """
    table: dict[str, str] = {}
    for codepoint in range(0x110000):
        if 0xD800 <= codepoint <= 0xDFFF:
            continue
        character = chr(codepoint)
        if character.lower() != character:
            continue
        folded = character.casefold()
        if folded != character:
            table[character] = folded
    return table


def render(table: dict[str, str]) -> str:
    """The table's entries and its pattern, in the shape format.ts spells."""
    keys = sorted(table)
    rows: list[str] = []
    row: list[str] = []
    for key in keys:
        row.append(f'  ["{key}", "{table[key]}"],')
        if len(row) == _PER_LINE:
            rows.append(" ".join(row))
            row = []
    if row:
        rows.append(" ".join(row))

    specials = {"\\", "]", "^", "-", "[", "/"}
    for key in keys:
        if key in specials:
            msg = f"key {key!r} needs escaping in the character class"
            raise SystemExit(msg)

    return (
        _BEGIN
        + "\n".join(rows)
        + "\n])\n"
        + "const FULL_FOLD_PATTERN = /["
        + "".join(keys)
        + "]/gu;"
    )


def region(source: str) -> tuple[int, int]:
    """The bounds of the generated region: marker through the pattern line.

    The region ends at the blank line before the docstring, so a region left
    by an older generator (or a bad edit) is replaced whole rather than
    spliced into, and cannot accumulate a stale duplicate.
    """
    start = source.find(_BEGIN)
    if start < 0:
        msg = "format.ts does not carry the generator marker"
        raise SystemExit(msg)
    pattern = source.find("\nconst FULL_FOLD_PATTERN = ", start)
    if pattern < 0:
        msg = "format.ts does not carry FULL_FOLD_PATTERN after the table"
        raise SystemExit(msg)
    end = source.index("\n\n", pattern)
    return start, end


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite format.ts (default: report whether it is stale)",
    )
    args = parser.parse_args(argv)

    source = _FORMAT_TS.read_text(encoding="utf-8")
    start, end = region(source)
    block = render(full_fold_table())
    stale = source[start:end] != block

    if args.write:
        if not stale:
            print("format.ts is already current")
            return 0
        _FORMAT_TS.write_text(source[:start] + block + source[end:], encoding="utf-8")
        print(f"rewrote {_FORMAT_TS.relative_to(_ROOT)}")
        return 0

    if stale:
        print(
            f"{_FORMAT_TS.relative_to(_ROOT)} is stale; "
            "run tools/gen_full_fold.py --write"
        )
        return 1
    print("format.ts matches str.casefold")
    return 0


if __name__ == "__main__":
    sys.exit(main())