"""Validate the dashboard's HTML and CSS with the Nu Html Checker (vnu.jar).

Two passes, one vnu runner:

  Static assets (``src/recoverage/assets``) — the source files as shipped.
  ``index.html`` is validated directly; the CSS files use ``--css``, which
  forces CSS-validation mode (vnu cannot parse a bare ``.css`` file as HTML).
  This pass used to be a separate Node script (``tools/lint_html.mjs``); it was
  folded in here because both passes need the same jar path, the same
  ``java -jar`` invocation and the same missing-jar message, and keeping them in
  two languages meant two places to update when that plumbing changed.

  Served documents — what a browser actually receives, which the static pass
  cannot see because the server assembles them: ``GET /`` (the SPA shell with
  ``style.css`` and ``app.js`` injected) and ``GET /potato`` (fully
  server-rendered).  Both use ``--also-check-css`` so the embedded CSS is
  validated too.  The 401 page ``--token`` answers a browser with is a
  constant (``server._UNAUTHORIZED_HTML``) sent as-is, so it is written out
  and checked strictly with no filter.

Potato Mode deliberately renders HTML4-era markup (``<font>``, ``bgcolor``,
``cellpadding``, ... — see the "no CSS" docstrings in potato.py).  The obsolete
family is filtered for that document as the documented retro contract, while
every other message stays fatal. The Tailwind stylesheet, as a file and inlined
in the shell, is checked strictly apart from ``TAILWIND_OUTPUT_FILTER``: three
messages vnu raises on valid Tailwind 4 output, named one by one. A canary run
plants an error in a copy of the stylesheet first, so a vnu that validates
nothing (as it did on the previous bundle) fails the gate instead of passing it.

The gate fails on any other vnu message of any severity: nothing is skipped
beyond those two documented filters.

Requires: uv (project venv), java on PATH, and ``bun install`` already run
(for vnu-jar).  Both are checked here and reported by name, so a run that
cannot start the checker says which input is missing rather than ending in a
``FileNotFoundError`` traceback from ``subprocess``.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

from _serve_harness import (
    build_sample_db,
    get,
    report_server_exit,
    running_server,
    scratch_project_dir,
    wait_for,
)

from recoverage.potato import _RENDER_ERROR_BODY, _db_unavailable_page, _no_data_page
from recoverage.server import _UNAUTHORIZED_HTML

REPO_ROOT = next(p for p in Path(__file__).resolve().parents if (p / "pyproject.toml").is_file())
VNU_JAR = REPO_ROOT / "node_modules" / "vnu-jar" / "build" / "dist" / "vnu.jar"
ASSETS_DIR = REPO_ROOT / "src" / "recoverage" / "assets"

#: Exit status for "the checker could not be started", kept apart from the
#: non-zero vnu itself returns for a finding.  The two are different answers:
#: one says the document is wrong, the other says nothing was checked, and a
#: CI log that renders them the same is a gate that reads as green-on-failure
#: to whoever triages it.
RUNNER_UNAVAILABLE = 3

#: How long one vnu pass may run before it is killed and reported as
#: :data:`RUNNER_UNAVAILABLE`.  A JVM validating the built bundle takes
#: seconds; a wedged one (an exhausted runner, a jar on a network mount that
#: never answers, a JVM stuck in a checker loop) blocks forever, and a gate
#: with no bound is a CI job that holds a runner until the job timeout kills
#: it with no line naming the command that hung.  600s leaves two orders of
#: magnitude over the ~10s a real pass costs on this bundle, so a slow runner
#: is not mistaken for a wedged one.  The kill is subprocess.run's own: it
#: SIGKILLs the child and reaps it, so nothing is left holding the runner.
VNU_TIMEOUT_SECONDS = 600.0

#: Shipped asset files vnu validates.  The list is explicit rather than globbed
#: so adding an asset is a deliberate choice. `style.css` is generated by the
#: Tailwind build from `web/`; it stays on the list because vnu is the only
#: check that sees the compiled CSS a browser actually receives.
HTML_FILES = ("index.html",)
CSS_FILES = ("print.css", "style.css")

#: The three messages vnu's CSS checker raises on valid Tailwind 4 output, and
#: nothing else. `@property` is CSS Properties and Values API Level 1, which the
#: checker does not implement; `margin-trim` only appears inside an `@supports`
#: test Tailwind uses to detect engines; a custom property in
#: `transition-property` is allowed by CSS Transitions Level 1. Every other
#: message on the stylesheet or the served shell still fails the gate.
TAILWIND_OUTPUT_FILTER = (
    ".*(Unrecognized at-rule “@property”"
    "|“margin-trim”: Property “margin-trim” doesn't exist"
    "|“transition-property”: “--tw-[a-z-]+” is not a “transition-property” value).*"
)

#: A declaration vnu has to reject. Appended to a copy of the built stylesheet,
#: it proves the CSS pass validated the file rather than skipping it: vnu
#: 26.9.16 reported nothing at all on the previous bundle, a planted typo
#: included, so a clean exit on its own was no evidence.
CSS_CANARY = "\n.vnu-canary{colr:red}\n"


def run_vnu(args: list[str], paths: list[str | Path]) -> int:
    """Run vnu over *paths*; return its exit status (non-zero = findings).

    Bounded by :data:`VNU_TIMEOUT_SECONDS`.  A pass that outlives it validated
    nothing, which is :data:`RUNNER_UNAVAILABLE` and not a finding: the
    distinction the status exists for is "the document is wrong" against
    "nothing was checked", and a hang is the second of those with no line of
    its own.
    """
    cmd = ["java", "-jar", str(VNU_JAR), *args, *(str(p) for p in paths)]
    print(f"vnu: {' '.join(cmd)}")
    try:
        return subprocess.run(cmd, timeout=VNU_TIMEOUT_SECONDS).returncode
    except subprocess.TimeoutExpired:
        print(
            f"vnu did not finish within {VNU_TIMEOUT_SECONDS:.0f}s and was killed; "
            "nothing was validated",
            file=sys.stderr,
        )
        return RUNNER_UNAVAILABLE
    except OSError as exc:
        # java was on PATH at the preflight and is not now, or the kernel
        # refused the exec. Either way nothing was validated, and that is not
        # the same answer as a document vnu rejected.
        print(f"could not run vnu: {exc}", file=sys.stderr)
        return RUNNER_UNAVAILABLE


def lint_static_assets(scratch: Path) -> int:
    """Validate the shipped assets; 0 when clean."""
    rc = run_vnu([], [ASSETS_DIR / f for f in HTML_FILES])
    if rc != 0:
        return rc
    canary = scratch / "style-canary.css"
    canary.write_text(
        (ASSETS_DIR / "style.css").read_text(encoding="utf-8") + CSS_CANARY, encoding="utf-8"
    )
    if run_vnu(["--css", "--filterpattern", TAILWIND_OUTPUT_FILTER], [canary]) == 0:
        print("vnu accepted a stylesheet with a planted error, so it validated nothing")
        return 1
    return run_vnu(
        ["--css", "--filterpattern", TAILWIND_OUTPUT_FILTER], [ASSETS_DIR / f for f in CSS_FILES]
    )


def main() -> int:
    if not VNU_JAR.is_file():
        print("vnu.jar not found; run `bun install` first.")
        return 2
    if shutil.which("java") is None:
        print(
            "java not on PATH; vnu-jar is a jar, so it runs under a JRE "
            "(Debian/Ubuntu: default-jre, brew: openjdk)."
        )
        return RUNNER_UNAVAILABLE

    with scratch_project_dir() as project_dir:
        rc = lint_static_assets(project_dir)
        if rc != 0:
            print("static-asset lint failed")
            return rc

        if not build_sample_db(project_dir).is_file():
            print("sample coverage document not built")
            return 1

        with running_server(project_dir) as (port, proc):
            if not wait_for(lambda: get(port, "/api/health")[0] == 200):
                print("server never became healthy")
                report_server_exit(proc)
                return 1

            docs: dict[str, Path] = {}
            for path, name in (("/", "spa.html"), ("/potato", "potato.html")):
                status, body = get(port, path)
                if status != 200:
                    print(f"GET {path} -> {status}; cannot lint served document")
                    return 1
                (project_dir / name).write_bytes(body)
                docs[name] = project_dir / name

            # SPA shell: strict apart from TAILWIND_OUTPUT_FILTER, the three
            # messages vnu raises on valid Tailwind 4 output in the inlined sheet.
            # Potato Mode: the obsolete-element/attribute family (<font>,
            # bgcolor, valign, ...) is the documented retro design, so hide
            # those messages; every other message still fails the gate.
            # (vnu's --filterpattern matches the full message, hence the .*)
            rc = run_vnu(
                ["--also-check-css", "--filterpattern", TAILWIND_OUTPUT_FILTER], [docs["spa.html"]]
            )
            if rc == 0:
                rc = run_vnu(
                    ["--also-check-css", "--filterpattern", ".*obsolete.*"],
                    [docs["potato.html"]],
                )
            if rc == 0:
                unauthorized = project_dir / "unauthorized.html"
                unauthorized.write_bytes(_UNAUTHORIZED_HTML)
                rc = run_vnu(["--also-check-css"], [unauthorized])
            # The three Potato fallback pages answer on a status no fetch above
            # reaches: 503 (the coverage directory is unreadable), 500 (a render
            # raised) and the "no data for target" page (a target the project
            # declares but nothing has built).  They are module constants, not a
            # 200 response, so the served-document pass never saw them — and the
            # 500 one was a bare ``<html><body>`` document, which is how a page
            # with no language, no title, no heading and no landmark shipped
            # past a gate that reported the tree as validated.  Written out and
            # checked STRICTLY: unlike the served Potato page these carry no
            # retro markup (see ``potato._FALLBACK_PAGE_STYLE``), so no
            # obsolete family needs filtering for them.
            if rc == 0:
                fallback_paths: list[str | Path] = []
                for name, document in (
                    ("potato-503.html", str(_db_unavailable_page().body)),
                    ("potato-500.html", _RENDER_ERROR_BODY),
                    ("potato-no-data.html", _no_data_page("SOME_TARGET")),
                ):
                    page = project_dir / name
                    page.write_text(document, encoding="utf-8")
                    fallback_paths.append(page)
                rc = run_vnu(["--also-check-css"], fallback_paths)
            if rc != 0:
                print("served-document lint failed")
                return rc

    print("HTML/CSS lint passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
